export const SET_CATEGORIES = 'SET_CATEGORIES'

export const SET_SORT_TYPE = 'SET_SORT_TYPE'

export const SET_POSTS = 'SET_POSTS'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

export const SET_POST_COMMENTS = 'SET_POST_COMMENTS'
export const ADD_POST_COMMENT = 'ADD_POST_COMMENT'
export const UPDATE_POST_COMMENT = 'UPDATE_POST_COMMENT'
export const DELETE_POST_COMMENT = 'DELETE_POST_COMMENT'
